### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Byron** [LumaPictures/LumaNukeGizmos#2]
Dear Luma,

Even though this plugin is used in many companies already, it's unclear to me under which license this happens. Legally, not specifying a license doesn't imply the right to use it.

Would you add license information to resolve the issue ?

Thank you,
Sebastian

**Comment by nrusch** [comment]
Thanks for the heads-up. This is resolved in e5b115a070025bc9278ef35a068338c33b5702e8.
